### ISSUE TITLE
tpfan-ui crashes if i try to do anything

### ISSUE THREAD

**Issue by gnhartch** [zocker-160/thinkfan-ui#8] opened 2023-06-26 15:23 UTC
downloaded the dot deb file and installed everything fine, just keep getting this errror

```
buttx@mukitown:~$ sudo thinkfan-ui
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
set speed: 5
OSError: [Errno 22] Invalid argument

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/thinkfan-ui/fan.py", line 180, in <lambda>
    self.button_set.clicked.connect(lambda: app.setFanSpeed(self.slider.value()))
  File "/usr/lib/thinkfan-ui/fan.py", line 159, in setFanSpeed
    soc.write(f"level {speed}")
OSError: [Errno 22] Invalid argument
/usr/bin/thinkfan-ui: line 3:  5175 Aborted                 python3 /usr/lib/thinkfan-ui/fan.py

```

**Comment by zocker-160** [comment] 2023-06-26 17:59
This looks exactly like the problem described in #3 and #7.

I sadly have no idea what is causing this given that the launch script is perfectly valid bash syntax.

**Comment by bootyberry** [comment] 2023-07-18 16:20
I ran into this problem, and it turns out you need to enable fan control on the thinkpad_acpi kernel module and reboot.
`
echo 'options thinkpad_acpi fan_control=1' | sudo tee -a /etc/modprobe.d/thinkpad_acpi.conf`

**Comment by zocker-160** [comment] 2023-07-18 16:41
> I ran into this problem, and it turns out you need to enable fan control on the thinkpad_acpi kernel module and reboot.
 echo 'options thinkpad_acpi fan_control=1' | sudo tee -a /etc/modprobe.d/thinkpad_acpi.conf

Does this actually fix the issue? I would be kinda surprised given that `thinkpad_acpi` should be enabled by default on every popular distribution.

If not have you tried my suggestions from the other issue: https://github.com/zocker-160/thinkfan-ui/issues/3#issuecomment-1057966542 and https://github.com/zocker-160/thinkfan-ui/issues/3#issuecomment-1057975822?

I know it sounds weird, but it seems to fix it for some ppl and I have no idea why that is.

**Comment by zocker-160** [comment] 2023-08-07 22:44
This issue should be fixed with the latest version. The problem is that both the DEB and the AUR package don't initialize the thinkpad_acpi kernel module correctly.

**Closed by zocker-160** 2023-08-07 22:44 UTC
Labels: duplicate
