### ISSUE TITLE
temp not displayed

### ISSUE THREAD

**Issue by gnhartch** [zocker-160/thinkfan-ui#5] opened 2023-01-25 21:18 UTC
just upgraded to latest version and temperature data is missing.

sensors in terminal pulls up data as expected but not displayed in thinkfan-ui application window :/

**Comment by zocker-160** [comment] 2023-01-25 23:14
can you please post the output of the `sensors` command here?

**Comment by gnhartch** [comment] 2023-01-26 08:56
```
[buttx@tartarus ~]$ sensors
coretemp-isa-0000
Adapter: ISA adapter
Package id 0:  +53.0°C  (high = +86.0°C, crit = +100.0°C)
Core 0:        +53.0°C  (high = +86.0°C, crit = +100.0°C)
Core 1:        +48.0°C  (high = +86.0°C, crit = +100.0°C)

BAT0-acpi-0
Adapter: ACPI interface
in0:          12.19 V  

thinkpad-isa-0000
Adapter: ISA adapter
fan1:        2880 RPM

acpitz-acpi-0
Adapter: ACPI interface
temp1:        +52.0°C  (crit = +99.0°C)

```

**Comment by zocker-160** [comment] 2023-01-26 10:26
thank you I will look into it

**Comment by blipk** [comment] 2023-01-28 06:44
I'm having a similar problem:
![image](https://user-images.githubusercontent.com/45532845/215251176-fc405397-06dd-4703-941a-d9b1c28434fc.png)

I'm not sure if this is related to @gnhartch issue as they didn't provide a screenshot, I'm also not sure if it's specific to thinkfan or a broken config on my system because I can fix it running with this QT env var:
`QT_QPA_PLATFORMTHEME=qt5ct thinkfan-ui`
![image](https://user-images.githubusercontent.com/45532845/215251249-23e834bb-ad72-47e5-b8b6-00b5cd4d37d1.png)

@zocker-160

**Comment by gnhartch** [comment] 2023-01-28 06:52
all the other information was displayed just not the CPU temp.

I tried solution from @blipk and it didn't change anything

**Comment by blipk** [comment] 2023-01-28 07:47
It was an issue with the regex from the last PR, I've opened a fix or discussion here:
https://github.com/zocker-160/thinkfan-ui/pull/6

**Comment by zocker-160** [comment] 2023-01-28 14:17
@blipk I cannot reproduce this issue and I do not think I can do anything about this, since I am not enforcing any QT theme nor are any colors hardcoded (except the version number, I will fix that), it should always use the system theme.

From my testing it does look correctly when using dark mode.

**Comment by zocker-160** [comment] 2023-01-28 14:25
thank you for reporting the issue @gnhartch, it should be fixed now, I will push new version in a few minutes.

**Closed** 2023-01-28 14:24 UTC
Labels: bug

**Comment by blipk** [comment] 2023-01-28 22:47
No worries @zocker-160 I figured it's probably my system, so all good.
