### ISSUE TITLE
thinkfan-ui crashes when clicking "full throttle"

### ISSUE THREAD

**Issue by FantasyPvP** [zocker-160/thinkfan-ui#7] opened 2023-06-22 13:34 UTC
my device is a thinkpad x1 yoga gen3, should thinkfan work for this device?

**Comment by FantasyPvP** [comment] 2023-06-22 13:37
i'm running arch with zen kernel 6.3.8 if that matters?

**Comment by zocker-160** [comment] 2023-06-22 13:44
Could you start with a terminal in command line and then press full throttle and give me the terminal output?

That would be really helpful to find out what is going wrong.

**Comment by FantasyPvP** [comment] 2023-06-22 17:40
![image](https://github.com/zocker-160/thinkfan-ui/assets/80643031/675934bf-fa59-4b7d-869d-7aaf95fe4631)
here's the screenshot, does this error mean my system isn't supported?
like I said, I'm running the latest zen kernel so maybe it doesnt support the thinkpad-acpi patch?

**Comment by zocker-160** [comment] 2023-06-22 18:31
ah I see, I remember seeing this issue some time ago already.

I guess the problem is that your shell does not seem to support the `"$@"` syntax, if you remove in `/usr/bin/thinkfan-ui`, it should start.

I had to add it in order to make commandline arguments work and weirdly enough it just does not work with some terminal emulators.

This is an issue that I wanted to fix by moving away from using a launch bash script.

**Comment by zocker-160** [comment] 2023-06-22 18:39
yep it is actually a duplicate of #3, the error looks exactly the same.

**Comment by FantasyPvP** [comment] 2023-06-27 11:14
> ah I see, I remember seeing this issue some time ago already.
> 
> I guess the problem is that your shell does not seem to support the `"$@"` syntax, if you remove in `/usr/bin/thinkfan-ui`, it should start.
> 
> I had to add it in order to make commandline arguments work and weirdly enough it just does not work with some terminal emulators.
> 
> This is an issue that I wanted to fix by moving away from using a launch bash script.
> 
> That being said, `"$@"` is valid POSIX syntax and should be reported as a bug to the terminal / shell emulator.

Just so you know I'm using bash with alacritty which I believe is quite a popular combination

**Comment by zocker-160** [comment] 2023-06-27 14:25
understood, thank you for that information, I will try to reproduce that issue (which so far I sadly have not been able to)

**Comment by zocker-160** [comment] 2023-06-27 14:33
I am sadly not able to reproduce this with bash + alacritty.

**Comment by zocker-160** [comment] 2023-08-07 22:44
This issue should be fixed with the latest version. The problem is that both the DEB and the AUR package don't initialize the `thinkpad_acpi` kernel module correctly.

**Closed by zocker-160** 2023-08-07 22:44 UTC
Labels: duplicate
